blank_issues_enabled: false
contact_links:
  - name: 💬 Start a Discussion
    url: https://github.com/mouakos/fastapi-monitoring-observability/discussions
    about: Have a question or want to share feedback? Start a discussion instead.
